// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jjfwpspbwbytxbfljmcz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpqZndwc3Bid2J5dHhiZmxqbWN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5OTUwMDMsImV4cCI6MjA3MjU3MTAwM30.caeCFkeweNvklgOJMvpoi_3hNf-lL8sTfEP5dJ8RHhU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});